- name: nodejs 
  include_role:
      name: common
      tasks_from: nodejs

- name: app setup
  include_role:
      name: common
      tasks_from: app_setup

- name: systemd
  include_role:
      name: common
      tasks_from: systemd

