- name: app setup
  include_roles:
      name: common
      tasks_from: app_setup

- name: python 
  include_roles:
      name: common
      tasks_from: python

- name: systemd
  include_roles:
      name: common
      tasks_from: systemd



