- name: install paython3 packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
  loop:
    - python3
    - python3-devel
    - gcc

- name: install python dependencies
  ansible.builtin.pip:
  requirements: /app/requirements.txt
  executable: pip3.9
  args:
    chdir: /app