- name: copy catalogue service file
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: systemctl deamon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Start and enable catalogue service
  ansible.builtin.service:
    name: catalogue
    state: restarted # Changed to restarted to avoid downtime
    enabled: yes
